name: Deploy deck
on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm i --frozen-lockfile
      - run: pnpm build   # emits ./out
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws s3 sync ./out s3://${{ secrets.S3_BUCKET }} --delete --exact-timestamps --cache-control "public,max-age=31536000,immutable" --exclude "index.html" --exclude "service-worker.js"
      - run: aws s3 cp ./out/index.html s3://${{ secrets.S3_BUCKET }}/index.html --cache-control "public,max-age=60,no-transform"
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"